// Optional browser acceptance: node tests/browser/dashboard.cjs [HTML path]
const { chromium } = require('playwright');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless: true, ...(process.env.REWIND_CHROMIUM ? {executablePath:process.env.REWIND_CHROMIUM,args:['--no-sandbox']} : {})});
  const page = await browser.newPage({viewport:{width:1440,height:1080}});
  const errors=[]; const network=[];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => {if(/^https?:/.test(r.url())) network.push(r.url())});
  await page.goto(pathToFileURL(path.resolve(process.argv[2] || '.rewind/demo.html')).href);
  assert.equal(await page.locator('#runCount').textContent(), '3');
  assert.equal(await page.locator('#replays').textContent(), '50');
  assert.match(await page.locator('#comparison').textContent(), /Boundary #3/);
  await page.locator('#jump').click();
  assert.equal(await page.locator('#scrubber').inputValue(), '3');
  assert.match(await page.locator('#response').textContent(), /720/);
  await page.locator('#next').click();
  assert.match(await page.locator('#state').textContent(), /720/);
  assert.match(await page.locator('#output').textContent(), /Scrub to the final/);
  await page.locator('#run').selectOption({index:2});
  assert.match(await page.locator('#mode').textContent(), /WHAT-IF/);
  await page.locator('#scrubber').fill('6');
  assert.match(await page.locator('#output').textContent(), /confirmed/);
  await page.locator('#search').fill('no-such-boundary');
  assert.match(await page.locator('#timeline').textContent(), /No matching/);
  await page.locator('#search').fill('');
  await page.locator('#run').selectOption({index:0});
  await page.locator('#jump').click();
  await page.screenshot({path:'.rewind/dashboard-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'.rewind/dashboard-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);assert.deepEqual(network,[]);
  console.log('PASS: timeline, scrubber, snapshot, comparison, fork lineage, search, mobile, no JS errors or network');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
